# we are adding this eureka properties because it is commen for all services
spring:
  application:
    name: Prod-Config

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
